import fs from "node:fs";
import path from "node:path";

const outputFilePath = path.join("src", "embedded-templates.ts");
const templatesDir = path.join("templates");

function listFilesRecursive(dir: string, base = ""): string[] {
	const results: string[] = [];
	for (const entry of fs.readdirSync(dir)) {
		const fullPath = path.join(dir, entry);
		const relativePath = base ? `${base}/${entry}` : entry;
		if (fs.statSync(fullPath).isDirectory()) {
			results.push(...listFilesRecursive(fullPath, relativePath));
		} else {
			results.push(relativePath);
		}
	}
	return results;
}

const files = listFilesRecursive(templatesDir);
const templateMap: Record<string, string> = {};

for (const file of files) {
	const fullPath = path.join(templatesDir, file);
	templateMap[file] = fs.readFileSync(fullPath).toString("base64");
}

const output = `// This file is generated by scripts/generate-embedded-templates.ts
// Do not edit manually.

export const embeddedTemplates: Record<string, string> = ${JSON.stringify(templateMap, null, "\t")};
`;

fs.writeFileSync(outputFilePath, output);
console.log(
	`Embedded templates generated at ${outputFilePath} (${files.length} files)`,
);
