name: deploy-site

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  setup-build-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Dependencies  
      run: npm install pnpm -g && pnpm install

    - name: Build
      run: pnpm build

    - name: Build Website
      run: pnpm website:build

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        command: pages deploy site/dist --project-name=docula --branch=main