name: deploy-site

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  setup-build-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies  
      run: npm install pnpm -g && pnpm install

    - name: Build
      run: pnpm build

    - name: Build Website
      run: pnpm build-site

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: b09b24c345713c704e71dea8bd81f713
        projectName: docula
        directory: site/dist
        branch: main
        gitHubToken: ${{ secrets.GH_TOKEN }}